### ISSUE TITLE
Feature Request: Show / List Connected or Active Users.

### ISSUE THREAD

**Issue by fieldmapper** [tkuester/taky#32]
```
$ takyclistatus

FreeTAKServer Active Users:
________________________________________________________________________________________________________
|   Health      |     CALLSIGN       |    IP Address    | Last Report                 | TAK Client     |
|  	Good		|   Field Mapper 	 |   192.168.1.100  | 2021-04-21 07:00:01 +0000   | ATAK-CIV 4.3.2 |
⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻⎻
```

Feature Request:

Above is just an example. Would be particularly useful to those who run FTS without a UI. Especially those who run lightweight installations - Raspberry Pi Zero, etc.

**Comment by tkuester** [comment]
I think this is an important feature -- I would also like to output various info about the server. Memory usage, number of open sockets, number of objects tracked in persistence.

However, right now, `takyctl` has no way of communicating with the host process. I think I'll need to add a unix control socket or something to achieve that... but it would also have the benefit of being able to kick off users, or send global announcements over chat (or something).

Since I'm already planning to add another server socket in 0.9, I'm going to assign this to that release.

**Comment by tkuester** [comment]
Some initial work in bba4169 and d1915cdd7.

Not all the fields are printed out in the table -- though I do have a command line option to output the status report as JSON which contains everything!
