### ISSUE TITLE
Add configuration -c to taky_dps & custom DPS port.

### ISSUE THREAD

**Issue by fieldmapper** [tkuester/taky#51]
Example:  
  
`taky_dps -c /etc/taky/taky-other.conf`  
  
and on taky.conf  
  
`[dp_server]`  
`upload_path = /var/taky/other/dp-user`  
`dp_port = 8444`  
  
This will enable taky\_dps to read another configuration file together with the correct certificate path to enable dual-server capability?

**Comment by pinztrek** [comment]
this would help quite a bit with dockerization. Really all files/dir paths for critical files should be able to be specified via command lines and also (ideally) via env variable. 

Would also help with testing configs, etc.

**Comment by tkuester** [comment]
`taky_dps` has always let you specify a manual config file -- but the port setting was ignored. I had assumed that the server would always be on 8080 or 8443, because it was hard coded in ATAK. I had never imagined that people would start using load balancers, but that makes perfect sense.

Now... I haven't yet added an option to allow the users to specify a separate IP address for the COT and DPS... is that a useful feature?

**Comment by tkuester** [comment]
Relevant commits: f644258

**Comment by scotte** [comment]
> I had assumed that the server would always be on 8080 or 8443, because it was hard coded in ATAK.

It's not actually hard coded, those are just the default values and can be changed in the atak plugin configuration.

**Comment by pinztrek** [comment]
The problem is that the data port in ATAK can be changed, but it impacts all servers. It's not set on a per server basis. 

You can change the port for individual servers for the main connection, just not the data package 

I watch the logs on my taky instance and it is a non-stop hacking attack if you expose 8443

I would have thought the certificate would have invalidated any attempts but they are still trying to access. 


On January 7, 2025 10:56:27 AM EST, Scott E ***@***.***> wrote:
>> I had assumed that the server would always be on 8080 or 8443, because it was hard coded in ATAK.
>
>It's not actually hard coded, those are just the default values and can be changed in the atak plugin configuration.
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/tkuester/taky/issues/51#issuecomment-2575644718
>You are receiving this because you commented.
>
>Message ID: ***@***.***>
Thanks,
Alan

**Comment by scotte** [comment]
Ah ha! Thank you for that clarification, I missed the nuance that it's global and not per server as with COT. My apologies, but it's good to be specific here. Thank you!
