### ISSUE TITLE
Using taky with nginx

### ISSUE THREAD

**Issue by jkimsis** [tkuester/taky#91]
Hello,

I've put taky on a Raspberry Pi 400 that's behind a router and already running a few webpages using nginx. I tried to set up nginx to put through the necessary ports for taky, but taky refuses to start afterwards because nginx is already listening to those ports. Has anyone used a similar setup? I have forwarded the ports to the RPI in the router, but that didn't seem to be enough.

**Comment by Matthew-Beckett** [comment]
Hi @jkimsis!

You can reconfigure the bind port for the CoT server in the taky.conf file, though I do not believe that the default port conflicts with NGINX and you thus I believe your issue is elsewhere in your configuration.

May I recommend switching to Docker and using nginx-proxy for automatic configuration as this would resolve a lot of your issues via automatic configuration.

Ultimately this is not an issue with taky and appears to a be a configuration issue in your specific deployment,

**Comment by tkuester** [comment]
@Matthew-Beckett -- Thanks for helping out the users!

@jkimsis Just because this is a more advanced usage / config issue, I'd like to close the issue and keep this related to the development. Or, if you think there could be some documentation to support this better, I'd welcome assistance maintaining that!

Closing for now.
